# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\python\yys-bot\qt\ui\script.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ScriptControler(object):
    def setupUi(self, ScriptControler):
        ScriptControler.setObjectName("ScriptControler")
        ScriptControler.resize(400, 300)
        self.gridLayoutWidget = QtWidgets.QWidget(ScriptControler)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 200, 111, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(ScriptControler)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(130, 200, 141, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listView = QtWidgets.QListView(self.horizontalLayoutWidget)
        self.listView.setObjectName("listView")
        self.horizontalLayout.addWidget(self.listView)
        self.tabWidget = QtWidgets.QTabWidget(ScriptControler)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 381, 181))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.splitter = QtWidgets.QSplitter(self.tab)
        self.splitter.setGeometry(QtCore.QRect(10, 20, 47, 48))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.radioButton_4 = QtWidgets.QRadioButton(self.splitter)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.splitter)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.splitter)
        self.radioButton_6.setObjectName("radioButton_6")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.splitter_2 = QtWidgets.QSplitter(self.tab_2)
        self.splitter_2.setGeometry(QtCore.QRect(0, 0, 47, 48))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.radioButton = QtWidgets.QRadioButton(self.splitter_2)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.splitter_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.splitter_2)
        self.radioButton_3.setObjectName("radioButton_3")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(ScriptControler)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(280, 200, 101, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listView_2 = QtWidgets.QListView(self.horizontalLayoutWidget_2)
        self.listView_2.setObjectName("listView_2")
        self.horizontalLayout_2.addWidget(self.listView_2)

        self.retranslateUi(ScriptControler)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ScriptControler)

    def retranslateUi(self, ScriptControler):
        _translate = QtCore.QCoreApplication.translate
        ScriptControler.setWindowTitle(_translate("ScriptControler", "Frame"))
        self.pushButton.setText(_translate("ScriptControler", "RUN"))
        self.comboBox.setItemText(0, _translate("ScriptControler", "AAA"))
        self.comboBox.setItemText(1, _translate("ScriptControler", "BBB"))
        self.comboBox.setItemText(2, _translate("ScriptControler", "CCC"))
        self.radioButton_4.setText(_translate("ScriptControler", "AAA1"))
        self.radioButton_5.setText(_translate("ScriptControler", "AAA2"))
        self.radioButton_6.setText(_translate("ScriptControler", "AAA3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ScriptControler", "AAA"))
        self.radioButton.setText(_translate("ScriptControler", "BBB1"))
        self.radioButton_2.setText(_translate("ScriptControler", "BBB2"))
        self.radioButton_3.setText(_translate("ScriptControler", "BBB3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ScriptControler", "BBB"))

